// The reverse map: Leva control path (inside its folder) -> store parameter key, per synced
// section. Pure data — levaSync.js walks it to push store values back into the panel when the
// STORE changes from somewhere other than the panel (a colour theme, the mobile loader overlay,
// HMR-restored state). If a control is not listed here it simply is not reverse-synced.

// Leva control path (inside its folder) → store param key, per synced section.
export const LEVA_SECTION_PATHS = Object.freeze({
    Terrain: {
        groundTexture: 'groundTextureEnabled',
        groundTextureName: 'groundTextureName',
        color: 'color',
        baseBrightness: 'baseBrightness',
        segments: 'segments',
        groundTextureScale: 'groundTextureScale',
        groundTextureContrast: 'groundTextureContrast',
        chunkSize: 'chunkSize',
    },
    // A folder inside World.Terrain, so it needs its own map — a folder adds a level to the leva
    // path and these would not resolve under 'World.Terrain'.
    'Ground Shadow': {
        shadowRadius: 'shadowRadius',
        shadowSoftness: 'shadowSoftness',
        shadowDarkness: 'shadowDarkness',
    },
    Background: {
        backgroundColor: 'backgroundColor',
        backgroundTexture: 'textureName',
        mixColor: 'skyMixColor',
        mixAmount: 'skyMixAmount',
        textureEnabled: 'textureEnabled',
        colorMode: 'colorMode',
        layer1Size: 'textureSize',
        layer2Scale: 'textureLayer2',
        textureYawParallax: 'textureYawParallax',
        texturePitchParallax: 'texturePitchParallax',
        textureContrast: 'textureContrast',
        textureBrightness: 'textureBrightness',
        textureMix: 'textureMixIntensity',
    },
    Stars: {
        starsEnabled: 'starsEnabled',
        starCellSize: 'starCellSize',
        starDensity: 'starDensity',
        starSize: 'starSize',
        starBrightness: 'starBrightness',
        starTwinkle: 'starTwinkleSpeed',
        starRays: 'starRays',
        starColor: 'starColor',
        starsFadeStart: 'starsFadeStart',
        starsFadeWidth: 'starsFadeWidth',
        skyRotation: 'rotationEnabled',
        skyRotationSpeed: 'rotationSpeed',
    },
    Border: {
        fadeMode: 'fadeMode',
        nStrength: 'noiseStrength',
        nScale: 'noiseScale',
        radius: 'circleRadiusFactor',
        edgeFade: 'groundFadeOffset',
        grassFade: 'grassFadeOffset',
        groundOffset: 'groundOffset',
        pSize: 'painterySize',
        pScreenBlend: 'painteryScreenBlend',
        pDrift: 'painteryDrift',
        pLayer2: 'painteryLayer2Scale',
    },
    Roads: {
        enabled: 'enabled',
        worldSeed: 'worldSeed',
        laneSpacing: 'laneSpacing',
        nodeSpacing: 'nodeSpacing',
        meander: 'meanderStrength',
        width: 'width',
        softness: 'softness',
        grassMinScale: 'grassMinScale',
        groundBrightness: 'groundBrightness',
        groundNoiseScale: 'groundNoiseScale',
        groundNoiseStrength: 'groundNoiseStrength',
        groundEdgeSharpness: 'groundEdgeSharpness',
    },
    Wind: {
        direction: 'direction',
        scale: 'scale',
        strength: 'strength',
        speed: 'speed',
    },
    // Tree wind lives with the other wind controls but writes objectParameters.
    WindTrees: {
        treeStrength: 'treeWindStrength',
        treeSpeed: 'treeWindSpeed',
        treeGust: 'treeWindGust',
    },
    Blades: {
        enabled: 'enabled',
        count: 'count',
        segments: 'segmentsCount',
        width: 'width',
        height: 'height',
        baseColor: 'colorBase',
        baseBrightness: 'baseBrightness',
    },
    Patches: {
        worldSeed: 'worldSeed',
        spacing: 'spacing',
        jitter: 'jitter',
        warpScale: 'domainWarpScale',
        warpStrength: 'domainWarpStrength',
        patchHeightVariation: 'patchHeightVariation',
        patchWidthVariation: 'patchWidthVariation',
        patchColorVariation: 'patchColorVariation',
        internalNoiseScale: 'internalNoiseScale',
        internalHeightVariation: 'internalHeightVariation',
        internalWidthVariation: 'internalWidthVariation',
        internalColorVariation: 'internalColorVariation',
        internalLeanVariation: 'internalLeanVariation',
        radialLean: 'radialLeanStrength',
        cameraFacing: 'cameraFacingStrength',
        orientationVariation: 'orientationVariation',
        borderWidth: 'borderWidth',
        borderMinScale: 'borderMinScale',
        tintCyan: 'tintColorCyan',
        tintViolet: 'tintColorViolet',
        tintYellow: 'tintColorYellow',
        tintGreen: 'tintColorGreen',
    },
    Trail: {
        enabled: 'trampleEnabled',
        trailStrength: 'trailStrength',
    },
    'Trail Dissolve': {
        enabled: 'dissolveEnabled',
        source: 'dissolveSource',
        radius: 'dissolveRadius',
        start: 'dissolveStart',
        end: 'dissolveEnd',
        rate: 'dissolveRate',
        amount: 'dissolveAmount',
        mode: 'dissolveMode',
    },
    'Trail Lighten': {
        enabled: 'lightenEnabled',
        source: 'lightenSource',
        radius: 'lightenRadius',
        start: 'lightenStart',
        end: 'lightenEnd',
        rate: 'lightenRate',
        amount: 'lightenAmount',
        color: 'lightenColor',
    },
    'Trail Scale': {
        enabled: 'scaleEnabled',
        source: 'scaleSource',
        radius: 'scaleRadius',
        start: 'scaleStart',
        end: 'scaleEnd',
        rate: 'scaleRate',
        amount: 'scaleAmount',
    },
    'Trail Lean': {
        enabled: 'leanEnabled',
        source: 'leanSource',
        radius: 'leanRadius',
        start: 'leanStart',
        end: 'leanEnd',
        rate: 'leanRate',
        amount: 'leanAmount',
    },
    Placement: {
        enabled: 'enabled',
        worldSeed: 'worldSeed',
        cellSize: 'cellSize',
        groupJitter: 'groupJitter',
        density: 'density',
        roadClearance: 'roadClearance',
        groupScale: 'groupScale',
        minObjectSpacing: 'minObjectSpacing',
        fadeOffset: 'fadeOffset',
        grassFadeDistance: 'grassFadeDistance',
        grassLean: 'grassLean',
    },
    Trees: {
        treeSize: 'treeSize',
        treeYOffset: 'treeYOffset',
        treeColor: 'treeColor',
        treeTrunkColor: 'treeTrunkColor',
        treeColorVariation: 'treeColorVariation',
    },
    Stones: {
        stoneSize: 'stoneSize',
        stoneYOffset: 'stoneYOffset',
        stoneTint: 'stoneTint',
        stoneColorVariation: 'stoneColorVariation',
        stoneGradientEnabled: 'stoneGradientEnabled',
        stoneGradientDark: 'stoneGradientDark',
        stoneGradientColor: 'stoneGradientColor',
        stoneGradientColorStrength: 'stoneGradientColorStrength',
        stoneGradientHeight: 'stoneGradientHeight',
    },
    Mushrooms: {
        mushroomSize: 'mushroomSize',
        mushroomYOffset: 'mushroomYOffset',
        mushroomCapColor: 'mushroomCapColor',
        mushroomLegColor: 'mushroomLegColor',
        mushroomColorVariation: 'mushroomColorVariation',
        mushroomLegColorVariation: 'mushroomLegColorVariation',
        mushroomGrassRadius: 'mushroomGrassRadius',
        mushroomGrassFade: 'mushroomGrassFade',
        mushroomGrassLean: 'mushroomGrassLean',
        mushroomWiggleRadius: 'mushroomWiggleRadius',
        mushroomWiggleAngle: 'mushroomWiggleAngle',
        mushroomWiggleSpeed: 'mushroomWiggleSpeed',
        mushroomWiggleDecay: 'mushroomWiggleDecay',
        mushroomLitBoost: 'mushroomLitBoost',
        mushroomSoundVolume: 'mushroomSoundVolume',
    },
    Surface: {
        painterly: 'painterlyEnabled',
        painterlyTexture: 'textureName',
        painterlyScale: 'painterlyScale',
        painterlyContrast: 'painterlyContrast',
        painterlyBrightness: 'painterlyBrightness',
        painterlyTint: 'painterlyColorStrength',
    },
    'Leaves Edge': {
        enabled: 'enabled',
        mode: 'mode',
        color: 'color',
        tint: 'tint',
        width: 'width',
        bias: 'bias',
        softness: 'softness',
        noiseScale: 'noiseScale',
        sharpness: 'sharpness',
    },
    'Rim Light': {
        enabled: 'enabled',
        stoneColor: 'stoneColor',
        trunkColor: 'trunkColor',
        mushroomColor: 'mushroomColor',
        musicStoneColor: 'musicStoneColor',
        strength: 'strength',
        power: 'power',
    },
    Hero: {
        modelScale: 'modelScale',
        modelYOffset: 'modelYOffset',
        rotationOffset: 'rotationOffset',
        idleTimeScale: 'idleTimeScale',
        runTimeScale: 'runTimeScale',
        runBlendInSpeed: 'runBlendInSpeed',
        runBlendOutSpeed: 'runBlendOutSpeed',
    },
    'Hero Material': {
        debug: 'debugMode',
        painterly: 'painterlyEnabled',
        pTexture: 'painterlyTexture',
        pScale: 'painterlyScale',
        pContrast: 'painterlyContrast',
        pBrightness: 'painterlyBrightnessVariation',
    },
    'Ground Light': {
        radius: 'radius',
        edgeSoftness: 'edgeSoftness',
        edgeNoiseScale: 'edgeNoiseScale',
        edgeNoiseStrength: 'edgeNoiseStrength',
        innerBrightness: 'innerBrightness',
        outerDarkness: 'outerDarkness',
    },
    'Color Grade': {
        highBrightnessMode: 'highBrightnessMode',
        'LOW (eye-safety).lowSaturation': 'lowSaturation',
        'LOW (eye-safety).lowWarmth': 'lowWarmth',
        'LOW (eye-safety).lowBrightness': 'lowBrightness',
        'HIGH (normal display).highSaturation': 'highSaturation',
        'HIGH (normal display).highWarmth': 'highWarmth',
        'HIGH (normal display).highBrightness': 'highBrightness',
    },
    'Painterly FX': {
        enabled: 'enabled',
        noiseSeed: 'noiseSeed',
        sensorNoise: 'sensorNoiseEnabled',
        lumaNoise: 'luminanceNoise',
        chromaNoise: 'chromaNoise',
        sensorScale: 'sensorNoiseScale',
    },
    Dithering: {
        pixelSize: 'pixelSize',
    },
    'Camera Debug': {
        debugOrbit: 'debugOrbit',
        debugOrbitAngle: 'debugOrbitAngle',
        debugOrbitDistance: 'debugOrbitDistance',
        debugOrbitHeight: 'debugOrbitHeight',
        debugTargetYOffset: 'debugTargetYOffset',
    },
    'Loader Debug': {
        enabled: 'enabled',
        targetX: 'targetX',
        targetZ: 'targetZ',
        step: 'nudgeStep',
        circleRadius: 'circleRadius',
        ringWidth: 'ringWidth',
        cameraY: 'cameraHeight',
    },
    'Mobile Loader': {
        loaderRadius: 'loaderRadius',
        loaderRingWidth: 'loaderRingWidth',
        loaderCameraHeight: 'loaderCameraHeight',
        loaderTargetX: 'loaderTargetX',
        loaderTargetZ: 'loaderTargetZ',
    },
    // Keys are the Leva control PATHS under "Desktop.UI" (incl. the subfolders the controls live in,
    // so the store→Leva reverse-sync hits the real fields); values are the gameUiParameters keys.
    'Game UI': {
        'Text & scale.uiScale': 'uiScale',
        'Text & scale.sizeFloor': 'sizeFloor',
        'Text & scale.sizeCeil': 'sizeCeil',
        'Text & scale.bubbleWidth': 'bubbleWidth',
        'Corners & frame.panelRadius': 'panelRadius',
        'Corners & frame.chipRadius': 'chipRadius',
        'Corners & frame.borderWidth': 'borderWidth',
        'Sound HUD.soundControlSize': 'soundControlSize',
        'Sound HUD.volFrameHeight': 'volFrameHeight',
        'Sound HUD.volSliderHeight': 'volSliderHeight',
        'Sound HUD.volSliderTrack': 'volSliderTrack',
        'Sound HUD.volSliderThumb': 'volSliderThumb',
        'Sound HUD.volEmptyOpacity': 'volEmptyOpacity',
        'Speech bubble.bubblePadX': 'bubblePadX',
        'Speech bubble.bubblePadY': 'bubblePadY',
        'Countdown.countSize': 'countSize',
        'Countdown.countBox': 'countBox',
        'Countdown.countBorder': 'countBorder',
        'Countdown.countNudge': 'countNudge',
        'Key chips.chipSize': 'chipSize',
        'Key chips.chipPadX': 'chipPadX',
        'Key chips.chipBorder': 'chipBorder',
        'Key chips.chipNudge': 'chipNudge',
        'Key chips.chipNudgeX': 'chipNudgeX',
        'Start button.startBtnSize': 'startBtnSize',
        'Start button.startBtnPadX': 'startBtnPadX',
        'Start button.startBtnPadY': 'startBtnPadY',
        'Credits buttons.creditsBtnSize': 'creditsBtnSize',
        'Credits buttons.creditsBtnPadX': 'creditsBtnPadX',
        'Credits buttons.creditsBtnPadY': 'creditsBtnPadY',
        'Credits buttons.creditsBtnOffset': 'creditsBtnOffset',
        'Dialogue reveal.wordStagger': 'wordStagger',
        'Dialogue reveal.wordFade': 'wordFade',
        'Tutorial.tutorialEnabled': 'tutorialEnabled',
        'Tutorial.tutorialImageSize': 'tutorialImageSize',
        'Tutorial.tutorialImageFrame': 'tutorialImageFrame',
        'Tutorial.tutorialFrameRadius': 'tutorialFrameRadius',
        'Tutorial.tutorialImageRadius': 'tutorialImageRadius',
        'Tutorial.tutorialPadding': 'tutorialPadding',
        'Tutorial.tutorialButtonOutside': 'tutorialButtonOutside',
    },
})
