export const painterlyPostDefaults = Object.freeze({
    enabled: false,
    noiseSeed: 0,
    sensorNoiseEnabled: true,
    luminanceNoise: 0.012,
    chromaNoise: 0.004,
    sensorNoiseScale: 1,
    bloomEnabled: true,
    bloomIntensity: 0.12,
    bloomThreshold: 0.4,
    bloomSmoothing: 0.1,
    bloomRadius: 0.5,
    sharpenEnabled: false,
    sharpenStrength: 0.35,
})
