export const painterlyPostDebugModes = Object.freeze({
    Final: 0,
    Original: 1,
    Displaced: 2,
    Tensor: 3,
    Kuwahara: 4,
    'Kuwahara + Original Edges': 5,
})

export const painterlyPostDefaults = Object.freeze({
    enabled: false,
    debugMode: painterlyPostDebugModes.Final,
    renderScale: 0.5,
    largeNoiseScale: 6,
    largeNoiseStrength: 1,
    fineNoiseScale: 120,
    fineNoiseStrength: 0.35,
    noiseSeed: 0,
    radius: 4,
    anisotropy: 1,
    eccentricity: 1,
    filterStrength: 1,
    edgeRestoreStrength: 1,
    edgeRestoreThreshold: 0,
    sensorNoiseEnabled: true,
    luminanceNoise: 0.012,
    chromaNoise: 0.004,
    sensorNoiseScale: 1,
    bloomEnabled: true,
    bloomIntensity: 0.12,
    bloomThreshold: 0.4,
    bloomSmoothing: 0.1,
    bloomRadius: 0.5,
    sharpenEnabled: true,
    sharpenStrength: 0.35,
})
