import { mainCharacterMaterialPresets } from './mainCharacterMaterials.js'
import { objectFieldDefaults } from './objectFieldDefaults.js'
import { painterlyPostDefaults } from './painterlyPostDefaults.js'
import { characterStylizedDefaults } from './stylizedMaterialDefaults.js'

function cloneMaterials(materials) {
    return Object.fromEntries(Object.entries(materials).map(([id, colors]) => [id, { ...colors }]))
}

const complexStyle = {
    label: 'Complex',
    terrainParameters: {
        color: '#454496',
        backgroundColor: '#403496',
        baseBrightness: 1,
        groundTextureEnabled: true,
        segments: 19,
        scale: 0.08,
        amplitude: 0,
        groundTextureScale: 0.05,
        groundTextureContrast: 0.45,
        chunkSize: 9,
    },
    grassParameters: {
        enabled: true,
        count: 1600,
        segmentsCount: 4,
        width: 0.28,
        height: 1.25,
        colorBase: '#028600',
        baseBrightness: 1,
        leanFactor: 0,

        // Grass-trail reaction — four independent layers. Each can read the fading
        // trail texture ('Trail') or a plain radius around the characters ('Radius'),
        // with its own falloff (start..end of the normalised influence + a rate curve).
        trampleEnabled: true,
        trailStrength: 0.7,

        dissolveEnabled: true,
        dissolveSource: 'Radius',
        dissolveRadius: 4.7,
        dissolveStart: 0.0,
        dissolveEnd: 0.88,
        dissolveRate: 2.15,
        dissolveAmount: 1.08,
        dissolveMode: 'Alpha',

        lightenEnabled: true,
        lightenSource: 'Trail',
        lightenRadius: 2.25,
        lightenStart: 0.02,
        lightenEnd: 0.47,
        lightenRate: 0.35,
        lightenAmount: 0.23,
        lightenColor: '#ff0518',

        scaleEnabled: true,
        scaleSource: 'Trail',
        scaleRadius: 2.75,
        scaleStart: 0.27,
        scaleEnd: 1.0,
        scaleRate: 0.8,
        scaleAmount: 0.59,

        leanEnabled: true,
        leanSource: 'Radius',
        leanRadius: 2.0,
        leanStart: 0.0,
        leanEnd: 0.67,
        leanRate: 0.8,
        leanAmount: 0.52,
    },
    grassPatchParameters: {
        worldSeed: 9187,
        spacing: 2.6,
        jitter: 0.07,
        domainWarpScale: 0.46,
        domainWarpStrength: 1.23,
        patchHeightVariation: 0.25,
        patchWidthVariation: 0.19,
        patchColorVariation: 0.28,
        internalNoiseScale: 0.54,
        internalHeightVariation: 0.28,
        internalWidthVariation: 0.4,
        internalColorVariation: 1,
        internalLeanVariation: 0.08,
        radialLeanStrength: 0.16,
        cameraFacingStrength: 0.08,
        orientationVariation: 0.14,
        borderWidth: 0.75,
        borderMinScale: 0.75,
        tintColorCyan: '#1d55ff',
        tintColorViolet: '#2843eb',
        tintColorYellow: '#6e35ff',
        tintColorGreen: '#5130ff',
        debugCenters: false,
        debugBorders: false,
        debugPatchColors: false,
    },
    roadParameters: {
        enabled: true,
        worldSeed: 4242,
        laneSpacing: 24,
        nodeSpacing: 10,
        meanderStrength: 11.6,
        width: 1.5,
        softness: 1.85,
        grassMinScale: 0,
        groundBrightness: -0.15,
        groundNoiseScale: 2,
        groundNoiseStrength: 2,
        groundEdgeSharpness: 1,
    },
    objectParameters: {
        ...objectFieldDefaults,
        painterlyEnabled: true,
        painterlyScale: 0.08,
        painterlyContrast: 1.05,
        painterlyBrightness: 0.5,
        painterlyColorStrength: 0,
        fadeOffset: 2.5,
    },
    windParameters: {
        direction: 0.65,
        scale: 0.35,
        strength: 0.2,
        speed: 1.1,
    },
    lanternGroundLightParameters: {
        radius: 3,
        edgeSoftness: 1.1,
        edgeNoiseScale: 0.39,
        edgeNoiseStrength: 0,
        innerBrightness: 0.4,
        outerDarkness: 0,
    },
    borderParameters: {
        fadeMode: 'Color',
        noiseStrength: 0.77,
        noiseScale: 0.23,
        circleRadiusFactor: 1,
        groundFadeOffset: 3,
        groundOffset: -2.4,
        grassFadeOffset: 3.66,
        painterySize: 167,
        painteryScreenBlend: 0.85,
        painteryDrift: 0.12,
        painteryLayer2Scale: 2.2,
        painteryBleed: 0.35,
    },
    ditheringParameters: {
        ditherMode: 'Bayer',
        pixelSize: 1,
    },
    backgroundParameters: {
        mode: 'Color',
        textureSize: 250,
        textureContrast: 0.4,
        textureLayer2: 2.3,
        starCellSize: 30,
        starDensity: 0.4,
        starSize: 0.06,
        starBrightness: 1.2,
        starTwinkleSpeed: 1.5,
        starRays: 0.35,
        starColor: '#fff8ff',
    },
    painterlyPostParameters: {
        ...painterlyPostDefaults,
    },
    // Stylized silhouette edge on the props (trees / rocks / mushrooms).
    edgeParameters: {
        enabled: true,
        mode: 'Dither', // Dither (opaque, stippled) | Alpha (transparent blend)
        color: '#2a2342',
        tint: 0.63,
        width: 6.0,
        bias: 0.4,
        softness: 0.23,
        noiseScale: 0.44,
    },
    characterParameters: {
        modelScale: 0.51,
        modelYOffset: 0.59,
        rotationOffset: 1.57,
        idleTimeScale: 1,
        runTimeScale: 1.2,
        runBlendInSpeed: 18,
        runBlendOutSpeed: 3,
    },
    characterMaterialParameters: {
        ...characterStylizedDefaults,
        materials: cloneMaterials(mainCharacterMaterialPresets.previous.materials),
    },
}

const complexPainteryStyle = {
    ...complexStyle,
    label: 'Complex Paintery',
    terrainParameters: {
        ...complexStyle.terrainParameters,
        backgroundColor: '#403496',
    },
    borderParameters: {
        ...complexStyle.borderParameters,
        fadeMode: 'Paintery',
        noiseStrength: 0.57,
        noiseScale: 0.3,
        circleRadiusFactor: 1.0,
        groundFadeOffset: 3.0,
        grassFadeOffset: 3.66,
        groundOffset: -3.0,
        painterySize: 500,
        painteryScreenBlend: 0.7,
        painteryDrift: 0.0,
        painteryLayer2Scale: 0.45,
        painteryBleed: 0.22,
    },
    backgroundParameters: {
        ...complexStyle.backgroundParameters,
        mode: 'Texture',
        textureSize: 500,
        textureContrast: 0.26,
        textureLayer2: 0.3,
    },
    gameUiParameters: {
        bubbleShape: 'Rect',
        buttonShape: 'Rect',
        roughness: 8.5,
        detail: 29,
        cornerRadius: 55,
        bubbleWidth: 760,
        textSize: 24,
        padding: 43,
        buttonWidth: 180,
        buttonHeight: 58,
        textureStrength: 1,
        textureScale: 600,
        fillColor: '#fef4ef',
        textColor: '#26285a',
    },
    seeThroughParameters: {
        enabled: true,
        worldRadius: 3.8,
        inner: 0.0,
        depthBias: 0.0,
        opacityIntensity: 0.7,
        textureContrast: 1.0,
        textureScale: 250,
    },
}

const flatColorsStyle = {
    ...complexStyle,
    label: 'Flat Colors',
    terrainParameters: {
        ...complexStyle.terrainParameters,
        groundTextureEnabled: false,
    },
    grassParameters: {
        ...complexStyle.grassParameters,
        enabled: false,
    },
    roadParameters: {
        ...complexStyle.roadParameters,
        enabled: false,
    },
    objectParameters: {
        ...complexStyle.objectParameters,
        enabled: false,
    },
    lanternGroundLightParameters: {
        ...complexStyle.lanternGroundLightParameters,
        radius: 3,
        edgeSoftness: 0,
        edgeNoiseScale: 0.39,
        edgeNoiseStrength: 0,
        innerBrightness: 0.4,
        outerDarkness: 0,
    },
    borderParameters: {
        ...complexStyle.borderParameters,
        fadeMode: 'Dither',
        noiseStrength: 0.08,
        noiseScale: 0.13,
        circleRadiusFactor: 1,
        groundFadeOffset: 0,
        grassFadeOffset: 2.45,
        groundOffset: -2.4,
    },
    painterlyPostParameters: {
        ...complexStyle.painterlyPostParameters,
        enabled: false,
    },
    characterMaterialParameters: {
        ...complexStyle.characterMaterialParameters,
        painterlyEnabled: false,
        materials: cloneMaterials(complexStyle.characterMaterialParameters.materials),
    },
}

const magicGlowStyle = {
    ...complexStyle,
    label: 'Magic Glow',
    borderParameters: {
        ...complexStyle.borderParameters,
        fadeMode: 'Dither',
    },
    lanternGroundLightParameters: {
        ...complexStyle.lanternGroundLightParameters,
        radius: 3.55,
        edgeSoftness: 1.99,
        edgeNoiseScale: 0.39,
        edgeNoiseStrength: 0,
        innerBrightness: 2.0,
        outerDarkness: 0,
    },
    painterlyPostParameters: {
        ...complexStyle.painterlyPostParameters,
        enabled: true,
        noiseSeed: 100,
        sensorNoiseEnabled: false,
        luminanceNoise: 0.2,
        chromaNoise: 0.1,
        sensorNoiseScale: 8,
        bloomEnabled: false,
        bloomIntensity: 2,
        bloomThreshold: 1,
        bloomSmoothing: 1,
        bloomRadius: 0.5,
        sharpenEnabled: true,
        sharpenStrength: 1,
    },
}

const painteryStyle = {
    ...complexStyle,
    label: 'Paintery',
    terrainParameters: {
        ...complexStyle.terrainParameters,
        color: '#747dff',
        backgroundColor: '#3d1f95',
        baseBrightness: 0.66,
        segments: 19,
        scale: 0.08,
        amplitude: 0,
        groundTextureScale: 0.05,
        groundTextureContrast: 0.45,
        chunkSize: 9,
    },

    grassParameters: {
        ...complexStyle.grassParameters,
        enabled: true,
        baseColor: '#6aa1a1',
        baseBrightness: 2.0,

        lightenEnabled: true,
        lightenSource: 'Trail',
        lightenRadius: 2.25,
        lightenStart: 0.02,
        lightenEnd: 0.47,
        lightenRate: 0.6,
        lightenAmount: 0.3,
        lightenColor: '#ff00e6',
    },
    borderParameters: {
        ...complexStyle.borderParameters,
        fadeMode: 'Paintery',
        noiseStrength: 0.57,
        noiseScale: 0.3,
        circleRadiusFactor: 1.0,
        groundFadeOffset: 3.0,
        grassFadeOffset: 3.66,
        groundOffset: -3.0,
        painterySize: 1120,
        painteryScreenBlend: 1.0,
        painteryDrift: 0.16,
        painteryLayer2Scale: 0.8,
        painteryBleed: 0.0,
    },
    backgroundParameters: {
        ...complexStyle.backgroundParameters,
        mode: 'Texture',
        textureSize: 599,
        textureContrast: 0.26,
        textureLayer2: 0.35,
        starCellSize: 30,
        starDensity: 0.4,
        starSize: 0.06,
        starBrightness: 1.2,
        starTwinkleSpeed: 1.5,
        starRays: 0.35,
        starColor: '#fff8ff',
    },
    lanternGroundLightParameters: {
        ...complexStyle.lanternGroundLightParameters,
        radius: 3.0,
        edgeSoftness: 1.99,
        edgeNoiseScale: 0.39,
        edgeNoiseStrength: 0,
        innerBrightness: 1.2,
        outerDarkness: 0,
    },
    painterlyPostParameters: {
        ...complexStyle.painterlyPostParameters,
        enabled: true,
        noiseSeed: 0,
        sensorNoiseEnabled: true,
        luminanceNoise: 0.02,
        chromaNoise: 0.02,
        sensorNoiseScale: 1,
        bloomEnabled: false,
        bloomIntensity: 0.0,
        bloomThreshold: 0.34,
        bloomSmoothing: 0.36,
        bloomRadius: 0.5,
        sharpenEnabled: false,
        sharpenStrength: 0.28,
    },
    gameUiParameters: {
        bubbleShape: 'Rect',
        buttonShape: 'Rect',
        roughness: 8.5,
        detail: 29,
        cornerRadius: 55,
        bubbleWidth: 760,
        textSize: 24,
        padding: 43,
        buttonWidth: 180,
        buttonHeight: 58,
        textureStrength: 1,
        textureScale: 600,
        fillColor: '#fef4ef',
        textColor: '#26285a',
    },
    seeThroughParameters: {
        enabled: true,
        worldRadius: 1.8,
        inner: 0.53,
        depthBias: 0.0,
        opacityIntensity: 0.7,
        textureContrast: 1.0,
        textureScale: 250,
    },
}

export const sceneStylePresets = Object.freeze({
    complex: complexStyle,
    complexPaintery: complexPainteryStyle,
    flatColors: flatColorsStyle,
    magicGlow: magicGlowStyle,
    paintery: painteryStyle,
})

export const defaultSceneStyleId = 'paintery'
export const defaultSceneStyle = sceneStylePresets[defaultSceneStyleId]

export function cloneSceneStyleSection(section) {
    if (!section) return section
    if (!section.materials) return { ...section }

    return {
        ...section,
        materials: cloneMaterials(section.materials),
    }
}
